apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-api-crds
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            stack: k8s-foundation
  template:
    metadata:
      name: "{{.name}}-gateway-api-crds"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-200"
    spec:
      project: "{{.name}}"
      destination:
        server: "{{.server}}"
      source:
        repoURL: https://github.com/kubernetes-sigs/gateway-api
        path: config/crd/standard
        targetRevision: v1.2.1
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
