apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: garagehq
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            stack: k8s-foundation
  template:
    metadata:
      name: "{{.name}}-garagehq"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
    spec:
      project: "{{.name}}"
      destination:
        server: "{{.server}}"
        namespace: storage-config
      source:
        repoURL: https://github.com/ClubCedille/k8s-foundation.git
        path: common/garage/resources
        targetRevision: master
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
