apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kf-velero
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            stack: k8s-foundation
  template:
    metadata:
      name: "{{.name}}-velero"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-1000"
    spec:
      destination:
        namespace: velero
        server: "{{.server}}"
      project: "{{.name}}"
      source:
        repoURL: https://github.com/ClubCedille/k8s-foundation.git
        targetRevision: HEAD
        path: common/velero/overlays/{{.name}}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/warn: privileged
            pod-security.kubernetes.io/audit: privileged
        syncOptions:
          - CreateNamespace=true
