apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/roles.yaml
  - resources/cluster-role.yaml
  - resources/policies.yaml
  - resources/secret-engine.yaml
  - resources/password-policy.yaml
  - resources/github-secret-engine.yaml

helmCharts:
  - name: vault
    version: "0.32.0"
    repo: "https://helm.releases.hashicorp.com"
    releaseName: "vault"
    namespace: vault
    valuesFile: "helm/vault.values.yaml"

  - name: vault-secrets-operator
    version: "1.4.0"
    repo: "https://helm.releases.hashicorp.com"
    releaseName: "vault-secrets-operator"
    namespace: vault
    valuesFile: "helm/vault-secrets-operator.values.yaml"
    includeCRDs: true

  - name: vault-config-operator
    version: "0.8.49"
    repo: "https://redhat-cop.github.io/vault-config-operator"
    releaseName: "vault-config-operator"
    namespace: vault
    valuesFile: "helm/vault-config-operator.values.yaml"
    includeCRDs: true

patches:
  - target:
      group: secrets.hashicorp.com
      version: v1beta1
      kind: VaultAuth
      name: vault-secrets-operator-default-transit-auth
    patch: |
      - op: replace
        path: /spec/namespace
        value: ""
