apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kf-rook-ceph-external
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            stack: k8s-foundation
  template:
    metadata:
      name: "{{.name}}-rook"
      namespace: argocd
    spec:
      destination:
        namespace: rook-ceph-external
        server: "{{.server}}"
      project: "{{.name}}"
      source:
        repoURL: https://github.com/ClubCedille/k8s-foundation.git
        path: common/rook/ressources
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
