apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium-ip-pools
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            stack: k8s-foundation
  template:
    metadata:
      name: "{{.name}}-cilium-ip-pools"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-80"
    spec:
      project: "{{.name}}"
      destination:
        server: "{{.server}}"
      source:
        repoURL: https://github.com/ClubCedille/k8s-foundation.git
        path: common/cilium-ip-pools/overlays/{{.name}}
        targetRevision: master
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
